import type { SkillMeta } from '../types';

export const DEMO_SKILLS: SkillMeta[] = [
  {
    id: 'langchain-tools',
    name: 'LangChain Tools',
    description: 'A comprehensive toolkit for building LLM-powered applications with chains, agents, and memory modules.',
    longDescription: '# LangChain Tools\n\nBuild powerful LLM applications with composable chains, intelligent agents, and persistent memory.\n\n## Features\n\n- **Chain Builder**: Compose complex LLM workflows with sequential and parallel chains\n- **Agent Framework**: Create autonomous agents that can use tools and make decisions\n- **Memory System**: Persistent memory across conversations with multiple backend support\n- **Tool Integration**: Connect to 50+ external APIs and data sources\n- **Streaming Support**: Real-time token streaming for responsive UIs',
    author: 'hwchase17',
    version: '0.2.14',
    source: 'github',
    sourceUrl: 'https://github.com/langchain-ai/langchain',
    tags: ['AI', 'LLM', 'Python', 'Agent', 'Chain'],
    rating: 4.8,
    downloadCount: 78500,
    createdAt: '2022-10-17T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    features: [
      { name: 'Chain Builder', description: 'Compose LLM workflows with sequential/parallel chains', demoContent: 'from langchain.chains import SequentialChain\n\nchain = SequentialChain(chains=[summarize, translate])\nresult = chain.run(input_text)' },
      { name: 'Agent Framework', description: 'Create autonomous agents with tool usage', demoContent: 'agent = initialize_agent(tools, llm, agent="zero-shot-react-description")\nagent.run("What is the weather in Tokyo?")' },
      { name: 'Memory System', description: 'Persistent conversation memory', demoContent: 'memory = ConversationBufferMemory()\nconversation = ConversationChain(llm=llm, memory=memory)' },
      { name: 'Tool Integration', description: 'Connect to 50+ external APIs', demoContent: 'tools = [SearchTool(), CalculatorTool(), WikipediaTool()]\nagent = create_agent(tools=tools)' },
    ],
    requirements: ['Python 3.9+', 'pip', 'OpenAI API Key'],
    status: 'not_downloaded',
  },
  {
    id: 'autogen-skill',
    name: 'AutoGen Multi-Agent',
    description: 'Multi-agent conversation framework for building collaborative AI systems with code execution capabilities.',
    longDescription: '# AutoGen Multi-Agent\n\nEnables building next-gen LLM applications based on multi-agent conversations.\n\n## Features\n\n- **Multi-Agent Conversations**: Orchestrate complex multi-agent workflows\n- **Code Execution**: Safe code execution in Docker containers\n- **Human-in-the-loop**: Seamless human participation in agent conversations\n- **Customizable Agents**: Create agents with specialized roles and capabilities',
    author: 'microsoft',
    version: '0.3.2',
    source: 'github',
    sourceUrl: 'https://github.com/microsoft/autogen',
    tags: ['AI', 'Multi-Agent', 'Python', 'Microsoft', 'Automation'],
    rating: 4.7,
    downloadCount: 42300,
    createdAt: '2023-08-15T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
    features: [
      { name: 'Multi-Agent Setup', description: 'Configure multiple agents with different roles', demoContent: 'assistant = autogen.AssistantAgent("assistant", llm_config=llm_config)\nuser_proxy = autogen.UserProxyAgent("user_proxy")' },
      { name: 'Group Chat', description: 'Multi-agent group conversations', demoContent: 'groupchat = autogen.GroupChat(agents=[assistant, coder, reviewer])\nmanager = autogen.GroupChatManager(groupchat=groupchat)' },
      { name: 'Code Execution', description: 'Safe code execution in containers', demoContent: 'user_proxy.execute_code_blocks(code_blocks)\n# Output: Execution result with stdout/stderr' },
    ],
    requirements: ['Python 3.10+', 'Docker', 'OpenAI API Key'],
    status: 'not_downloaded',
  },
  {
    id: 'crew-ai-skill',
    name: 'CrewAI',
    description: 'Framework for orchestrating role-playing, autonomous AI agents that work together to accomplish complex tasks.',
    longDescription: '# CrewAI\n\nCutting-edge framework for orchestrating role-playing, autonomous AI agents.\n\n## Features\n\n- **Role-Based Agents**: Define agents with specific roles, goals, and backstories\n- **Task Delegation**: Intelligent task routing and delegation between agents\n- **Process Management**: Sequential and hierarchical process support\n- **Tool Ecosystem**: Built-in and custom tool integration',
    author: 'joaomdmoura',
    version: '0.28.0',
    source: 'github',
    sourceUrl: 'https://github.com/joaomdmoura/crewAI',
    tags: ['AI', 'Agent', 'Python', 'Orchestration', 'Role-Play'],
    rating: 4.6,
    downloadCount: 28700,
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2024-12-05T00:00:00Z',
    features: [
      { name: 'Agent Creation', description: 'Define agents with roles and backstories', demoContent: 'researcher = Agent(\n  role="Senior Research Analyst",\n  goal="Uncover cutting-edge developments",\n  backstory="You work at a leading tech think tank."\n)' },
      { name: 'Task Definition', description: 'Create and assign tasks', demoContent: 'research_task = Task(\n  description="Research the latest AI trends",\n  agent=researcher,\n  expected_output="A comprehensive report"\n)' },
      { name: 'Crew Execution', description: 'Run collaborative agent crews', demoContent: 'crew = Crew(agents=[researcher, writer], tasks=[research_task, writing_task])\nresult = crew.kickoff()' },
    ],
    requirements: ['Python 3.10+', 'pip'],
    status: 'not_downloaded',
  },
  {
    id: 'semantic-kernel',
    name: 'Semantic Kernel',
    description: 'Microsoft SDK for integrating LLMs into conventional programming languages with plugins and planners.',
    longDescription: '# Semantic Kernel\n\nLightweight SDK that lets you add LLM capabilities to your apps with minimal code.\n\n## Features\n\n- **Plugin System**: Create reusable AI plugins\n- **Planner**: Automatic function chaining\n- **Memory**: Semantic memory with embeddings\n- **Multi-Language**: C#, Python, and Java support',
    author: 'microsoft',
    version: '1.3.0',
    source: 'github',
    sourceUrl: 'https://github.com/microsoft/semantic-kernel',
    tags: ['AI', 'SDK', 'C#', 'Python', 'Microsoft', 'Plugin'],
    rating: 4.5,
    downloadCount: 15200,
    createdAt: '2023-03-15T00:00:00Z',
    updatedAt: '2024-11-30T00:00:00Z',
    features: [
      { name: 'Plugin Creation', description: 'Build reusable AI plugins', demoContent: 'var kernel = new KernelBuilder()\n  .WithAzureChatCompletion(model, endpoint, key)\n  .Build();\nkernel.ImportPlugin(new TimePlugin());' },
      { name: 'Semantic Functions', description: 'Define AI functions with natural language', demoContent: 'var summarize = kernel.CreateFunctionFromPrompt("Summarize: {{$input}}");\nvar result = await kernel.InvokeAsync(summarize, new() { ["input"] = text });' },
    ],
    requirements: ['.NET 8+' , 'Python 3.10+'],
    status: 'not_downloaded',
  },
  {
    id: 'dify-platform',
    name: 'Dify',
    description: 'Open-source LLM app development platform combining AI workflow, RAG pipeline, and agent capabilities.',
    longDescription: '# Dify\n\nLLMOps platform for building and operating AI-native applications.\n\n## Features\n\n- **Visual Workflow**: Drag-and-drop AI pipeline builder\n- **RAG Engine**: Document-based retrieval augmented generation\n- **Agent Mode**: Autonomous agent with tool usage\n- **API-First**: Every app comes with an API',
    author: 'langgenius',
    version: '0.6.0',
    source: 'github',
    sourceUrl: 'https://github.com/langgenius/dify',
    tags: ['AI', 'Platform', 'LLM', 'RAG', 'Low-Code', 'Vue'],
    rating: 4.9,
    downloadCount: 52100,
    createdAt: '2023-04-12T00:00:00Z',
    updatedAt: '2024-12-08T00:00:00Z',
    features: [
      { name: 'Visual Workflow', description: 'Drag-and-drop AI pipeline builder', demoContent: '1. Add LLM Node (GPT-4)\n2. Add Knowledge Retrieval Node\n3. Add Code Execution Node\n4. Connect and Deploy' },
      { name: 'RAG Pipeline', description: 'Document-based question answering', demoContent: 'Upload PDF → Auto-chunk → Embedding → Vector Store\nQuery: "What is the main finding?" → RAG Response' },
      { name: 'Agent Mode', description: 'Autonomous AI agents', demoContent: 'Agent = create_agent(model="gpt-4", tools=[web_search, calculator])\nAgent.run("Plan a trip to Japan with budget $3000")' },
    ],
    requirements: ['Docker', 'Docker Compose', '4GB RAM'],
    status: 'not_downloaded',
  },
  {
    id: 'llama-index',
    name: 'LlamaIndex',
    description: 'Data framework for LLM applications to ingest, structure, and access private or domain-specific data.',
    longDescription: '# LlamaIndex\n\nYour data framework for LLM applications. Connect custom data sources to LLMs.\n\n## Features\n\n- **Data Connectors**: 160+ data source integrations\n- **Index Types**: Vector, tree, keyword, and knowledge graph indices\n- **Query Engine**: Advanced querying with routing and decomposition\n- **Agent Layer**: Tool-using agents for complex queries',
    author: 'run-llama',
    version: '0.10.0',
    source: 'github',
    sourceUrl: 'https://github.com/run-llama/llama_index',
    tags: ['AI', 'RAG', 'Python', 'Data', 'Indexing'],
    rating: 4.7,
    downloadCount: 35800,
    createdAt: '2022-11-01T00:00:00Z',
    updatedAt: '2024-12-03T00:00:00Z',
    features: [
      { name: 'Data Ingestion', description: 'Load data from 160+ sources', demoContent: 'documents = SimpleDirectoryReader("./data").load_data()\nindex = VectorStoreIndex.from_documents(documents)' },
      { name: 'Query Engine', description: 'Advanced data querying', demoContent: 'query_engine = index.as_query_engine()\nresponse = query_engine.query("Summarize the key findings")' },
    ],
    requirements: ['Python 3.9+', 'pip', 'OpenAI API Key'],
    status: 'not_downloaded',
  },
  {
    id: 'pdf-parser-skill',
    name: 'PDF Parser Pro',
    description: 'Advanced PDF parsing with OCR, table extraction, and structured output for AI document processing.',
    longDescription: '# PDF Parser Pro\n\nEnterprise-grade PDF parsing for AI applications.\n\n## Features\n\n- **Text Extraction**: Clean text extraction with layout preservation\n- **Table Detection**: Automatic table recognition and extraction\n- **OCR Support**: Optical character recognition for scanned documents\n- **Structured Output**: JSON/Markdown output formats',
    author: 'doc-parser',
    version: '2.1.0',
    source: 'github',
    sourceUrl: 'https://github.com/example/pdf-parser-pro',
    tags: ['Document', 'PDF', 'OCR', 'Python', 'Data'],
    rating: 4.3,
    downloadCount: 8900,
    createdAt: '2023-06-20T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
    features: [
      { name: 'Text Extraction', description: 'Layout-preserving text extraction', demoContent: 'parser = PDFParser(ocr_enabled=True)\nresult = parser.parse("report.pdf")\nprint(result.text)  # Clean extracted text' },
      { name: 'Table Extraction', description: 'Automatic table detection', demoContent: 'tables = parser.extract_tables("report.pdf")\nfor table in tables:\n  print(table.to_dataframe())' },
    ],
    requirements: ['Python 3.9+', 'Tesseract OCR'],
    status: 'not_downloaded',
  },
  {
    id: 'web-scraper-skill',
    name: 'WebScraper AI',
    description: 'Intelligent web scraping with AI-powered content extraction, anti-bot handling, and structured data output.',
    longDescription: '# WebScraper AI\n\nNext-generation web scraping with AI intelligence.\n\n## Features\n\n- **Smart Extraction**: AI-powered content identification\n- **Anti-Bot**: Advanced proxy and browser fingerprinting\n- **Scheduling**: Cron-based scraping schedules\n- **Data Pipeline**: Built-in data cleaning and export',
    author: 'webscrape-team',
    version: '1.5.0',
    source: 'github',
    sourceUrl: 'https://github.com/example/webscraper-ai',
    tags: ['Web', 'Scraping', 'Python', 'Automation', 'Data'],
    rating: 4.2,
    downloadCount: 12400,
    createdAt: '2023-09-01T00:00:00Z',
    updatedAt: '2024-11-28T00:00:00Z',
    features: [
      { name: 'Smart Scraping', description: 'AI-powered content extraction', demoContent: 'scraper = AIScraper(target="https://example.com/products")\ndata = scraper.extract(selectors=["title", "price", "rating"])' },
      { name: 'Batch Processing', description: 'Parallel URL processing', demoContent: 'urls = ["https://site1.com", "https://site2.com"]\nresults = scraper.batch_scrape(urls, max_concurrent=5)' },
    ],
    requirements: ['Python 3.10+', 'Playwright'],
    status: 'not_downloaded',
  },
];
