import type { SkillMeta } from '../types';

export const DEMO_SKILLS: SkillMeta[] = [
  {
    id: 'langchain-tools',
    name: 'LangChain Tools',
    description: 'A comprehensive toolkit for building LLM-powered applications with chains, agents, and memory modules.',
    longDescription: '# LangChain Tools\n\nBuild powerful LLM applications with composable chains, intelligent agents, and persistent memory.\n\n## Features\n\n- **Chain Builder**: Compose complex LLM workflows with sequential and parallel chains\n- **Agent Framework**: Create autonomous agents that can use tools and make decisions\n- **Memory System**: Persistent memory across conversations with multiple backend support\n- **Tool Integration**: Connect to 50+ external APIs and data sources\n- **Streaming Support**: Real-time token streaming for responsive UIs',
    author: 'hwchase17',
    version: '0.2.14',
    source: 'github',
    sourceUrl: 'https://github.com/langchain-ai/langchain',
    tags: ['AI', 'LLM', 'Python', 'Agent', 'Chain'],
    rating: 4.8,
    downloadCount: 78500,
    createdAt: '2022-10-17T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    features: [
      { name: 'Chain Builder', description: 'Compose LLM workflows with sequential/parallel chains', demoContent: 'from langchain.chains import SequentialChain\n\nchain = SequentialChain(chains=[summarize, translate])\nresult = chain.run(input_text)' },
      { name: 'Agent Framework', description: 'Create autonomous agents with tool usage', demoContent: 'agent = initialize_agent(tools, llm, agent="zero-shot-react-description")\nagent.run("What is the weather in Tokyo?")' },
      { name: 'Memory System', description: 'Persistent conversation memory', demoContent: 'memory = ConversationBufferMemory()\nconversation = ConversationChain(llm=llm, memory=memory)' },
      { name: 'Tool Integration', description: 'Connect to 50+ external APIs', demoContent: 'tools = [SearchTool(), CalculatorTool(), WikipediaTool()]\nagent = create_agent(tools=tools)' },
    ],
    requirements: ['Python 3.9+', 'pip', 'OpenAI API Key'],
    status: 'not_downloaded',
  },
  {
    id: 'autogen-skill',
    name: 'AutoGen Multi-Agent',
    description: 'Multi-agent conversation framework for building collaborative AI systems with code execution capabilities.',
    longDescription: '# AutoGen Multi-Agent\n\nEnables building next-gen LLM applications based on multi-agent conversations.\n\n## Features\n\n- **Multi-Agent Conversations**: Orchestrate complex multi-agent workflows\n- **Code Execution**: Safe code execution in Docker containers\n- **Human-in-the-loop**: Seamless human participation in agent conversations\n- **Customizable Agents**: Create agents with specialized roles and capabilities',
    author: 'microsoft',
    version: '0.3.2',
    source: 'github',
    sourceUrl: 'https://github.com/microsoft/autogen',
    tags: ['AI', 'Multi-Agent', 'Python', 'Microsoft', 'Automation'],
    rating: 4.7,
    downloadCount: 42300,
    createdAt: '2023-08-15T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
    features: [
      { name: 'Multi-Agent Setup', description: 'Configure multiple agents with different roles', demoContent: 'assistant = autogen.AssistantAgent("assistant", llm_config=llm_config)\nuser_proxy = autogen.UserProxyAgent("user_proxy")' },
      { name: 'Group Chat', description: 'Multi-agent group conversations', demoContent: 'groupchat = autogen.GroupChat(agents=[assistant, coder, reviewer])\nmanager = autogen.GroupChatManager(groupchat=groupchat)' },
      { name: 'Code Execution', description: 'Safe code execution in containers', demoContent: 'user_proxy.execute_code_blocks(code_blocks)\n# Output: Execution result with stdout/stderr' },
    ],
    requirements: ['Python 3.10+', 'Docker', 'OpenAI API Key'],
    status: 'not_downloaded',
  },
  {
    id: 'crew-ai-skill',
    name: 'CrewAI',
    description: 'Framework for orchestrating role-playing, autonomous AI agents that work together to accomplish complex tasks.',
    longDescription: '# CrewAI\n\nCutting-edge framework for orchestrating role-playing, autonomous AI agents.\n\n## Features\n\n- **Role-Based Agents**: Define agents with specific roles, goals, and backstories\n- **Task Delegation**: Intelligent task routing and delegation between agents\n- **Process Management**: Sequential and hierarchical process support\n- **Tool Ecosystem**: Built-in and custom tool integration',
    author: 'joaomdmoura',
    version: '0.28.0',
    source: 'github',
    sourceUrl: 'https://github.com/joaomdmoura/crewAI',
    tags: ['AI', 'Agent', 'Python', 'Orchestration', 'Role-Play'],
    rating: 4.6,
    downloadCount: 28700,
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2024-12-05T00:00:00Z',
    features: [
      { name: 'Agent Creation', description: 'Define agents with roles and backstories', demoContent: 'researcher = Agent(\n  role="Senior Research Analyst",\n  goal="Uncover cutting-edge developments",\n  backstory="You work at a leading tech think tank."\n)' },
      { name: 'Task Definition', description: 'Create and assign tasks', demoContent: 'research_task = Task(\n  description="Research the latest AI trends",\n  agent=researcher,\n  expected_output="A comprehensive report"\n)' },
      { name: 'Crew Execution', description: 'Run collaborative agent crews', demoContent: 'crew = Crew(agents=[researcher, writer], tasks=[research_task, writing_task])\nresult = crew.kickoff()' },
    ],
    requirements: ['Python 3.10+', 'pip'],
    status: 'not_downloaded',
  },
  {
    id: 'semantic-kernel',
    name: 'Semantic Kernel',
    description: 'Microsoft SDK for integrating LLMs into conventional programming languages with plugins and planners.',
    longDescription: '# Semantic Kernel\n\nLightweight SDK that lets you add LLM capabilities to your apps with minimal code.\n\n## Features\n\n- **Plugin System**: Create reusable AI plugins\n- **Planner**: Automatic function chaining\n- **Memory**: Semantic memory with embeddings\n- **Multi-Language**: C#, Python, and Java support',
    author: 'microsoft',
    version: '1.3.0',
    source: 'github',
    sourceUrl: 'https://github.com/microsoft/semantic-kernel',
    tags: ['AI', 'SDK', 'C#', 'Python', 'Microsoft', 'Plugin'],
    rating: 4.5,
    downloadCount: 15200,
    createdAt: '2023-03-15T00:00:00Z',
    updatedAt: '2024-11-30T00:00:00Z',
    features: [
      { name: 'Plugin Creation', description: 'Build reusable AI plugins', demoContent: 'var kernel = new KernelBuilder()\n  .WithAzureChatCompletion(model, endpoint, key)\n  .Build();\nkernel.ImportPlugin(new TimePlugin());' },
      { name: 'Semantic Functions', description: 'Define AI functions with natural language', demoContent: 'var summarize = kernel.CreateFunctionFromPrompt("Summarize: {{$input}}");\nvar result = await kernel.InvokeAsync(summarize, new() { ["input"] = text });' },
    ],
    requirements: ['.NET 8+' , 'Python 3.10+'],
    status: 'not_downloaded',
  },
  {
    id: 'dify-platform',
    name: 'Dify',
    description: 'Open-source LLM app development platform combining AI workflow, RAG pipeline, and agent capabilities.',
    longDescription: '# Dify\n\nLLMOps platform for building and operating AI-native applications.\n\n## Features\n\n- **Visual Workflow**: Drag-and-drop AI pipeline builder\n- **RAG Engine**: Document-based retrieval augmented generation\n- **Agent Mode**: Autonomous agent with tool usage\n- **API-First**: Every app comes with an API',
    author: 'langgenius',
    version: '0.6.0',
    source: 'github',
    sourceUrl: 'https://github.com/langgenius/dify',
    tags: ['AI', 'Platform', 'LLM', 'RAG', 'Low-Code', 'Vue'],
    rating: 4.9,
    downloadCount: 52100,
    createdAt: '2023-04-12T00:00:00Z',
    updatedAt: '2024-12-08T00:00:00Z',
    features: [
      { name: 'Visual Workflow', description: 'Drag-and-drop AI pipeline builder', demoContent: '1. Add LLM Node (GPT-4)\n2. Add Knowledge Retrieval Node\n3. Add Code Execution Node\n4. Connect and Deploy' },
      { name: 'RAG Pipeline', description: 'Document-based question answering', demoContent: 'Upload PDF → Auto-chunk → Embedding → Vector Store\nQuery: "What is the main finding?" → RAG Response' },
      { name: 'Agent Mode', description: 'Autonomous AI agents', demoContent: 'Agent = create_agent(model="gpt-4", tools=[web_search, calculator])\nAgent.run("Plan a trip to Japan with budget $3000")' },
    ],
    requirements: ['Docker', 'Docker Compose', '4GB RAM'],
    status: 'not_downloaded',
  },
  {
    id: 'llama-index',
    name: 'LlamaIndex',
    description: 'Data framework for LLM applications to ingest, structure, and access private or domain-specific data.',
    longDescription: '# LlamaIndex\n\nYour data framework for LLM applications. Connect custom data sources to LLMs.\n\n## Features\n\n- **Data Connectors**: 160+ data source integrations\n- **Index Types**: Vector, tree, keyword, and knowledge graph indices\n- **Query Engine**: Advanced querying with routing and decomposition\n- **Agent Layer**: Tool-using agents for complex queries',
    author: 'run-llama',
    version: '0.10.0',
    source: 'github',
    sourceUrl: 'https://github.com/run-llama/llama_index',
    tags: ['AI', 'RAG', 'Python', 'Data', 'Indexing'],
    rating: 4.7,
    downloadCount: 35800,
    createdAt: '2022-11-01T00:00:00Z',
    updatedAt: '2024-12-03T00:00:00Z',
    features: [
      { name: 'Data Ingestion', description: 'Load data from 160+ sources', demoContent: 'documents = SimpleDirectoryReader("./data").load_data()\nindex = VectorStoreIndex.from_documents(documents)' },
      { name: 'Query Engine', description: 'Advanced data querying', demoContent: 'query_engine = index.as_query_engine()\nresponse = query_engine.query("Summarize the key findings")' },
    ],
    requirements: ['Python 3.9+', 'pip', 'OpenAI API Key'],
    status: 'not_downloaded',
  },
  {
    id: 'pdf-parser-skill',
    name: 'PDF Parser Pro',
    description: 'Advanced PDF parsing with OCR, table extraction, and structured output for AI document processing.',
    longDescription: '# PDF Parser Pro\n\nEnterprise-grade PDF parsing for AI applications.\n\n## Features\n\n- **Text Extraction**: Clean text extraction with layout preservation\n- **Table Detection**: Automatic table recognition and extraction\n- **OCR Support**: Optical character recognition for scanned documents\n- **Structured Output**: JSON/Markdown output formats',
    author: 'doc-parser',
    version: '2.1.0',
    source: 'github',
    sourceUrl: 'https://github.com/example/pdf-parser-pro',
    tags: ['Document', 'PDF', 'OCR', 'Python', 'Data'],
    rating: 4.3,
    downloadCount: 8900,
    createdAt: '2023-06-20T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
    features: [
      { name: 'Text Extraction', description: 'Layout-preserving text extraction', demoContent: 'parser = PDFParser(ocr_enabled=True)\nresult = parser.parse("report.pdf")\nprint(result.text)  # Clean extracted text' },
      { name: 'Table Extraction', description: 'Automatic table detection', demoContent: 'tables = parser.extract_tables("report.pdf")\nfor table in tables:\n  print(table.to_dataframe())' },
    ],
    requirements: ['Python 3.9+', 'Tesseract OCR'],
    status: 'not_downloaded',
  },
  {
    id: 'web-scraper-skill',
    name: 'WebScraper AI',
    description: 'Intelligent web scraping with AI-powered content extraction, anti-bot handling, and structured data output.',
    longDescription: '# WebScraper AI\n\nNext-generation web scraping with AI intelligence.\n\n## Features\n\n- **Smart Extraction**: AI-powered content identification\n- **Anti-Bot**: Advanced proxy and browser fingerprinting\n- **Scheduling**: Cron-based scraping schedules\n- **Data Pipeline**: Built-in data cleaning and export',
    author: 'webscrape-team',
    version: '1.5.0',
    source: 'github',
    sourceUrl: 'https://github.com/example/webscraper-ai',
    tags: ['Web', 'Scraping', 'Python', 'Automation', 'Data'],
    rating: 4.2,
    downloadCount: 12400,
    createdAt: '2023-09-01T00:00:00Z',
    updatedAt: '2024-11-28T00:00:00Z',
    features: [
      { name: 'Smart Scraping', description: 'AI-powered content extraction', demoContent: 'scraper = AIScraper(target="https://example.com/products")\ndata = scraper.extract(selectors=["title", "price", "rating"])' },
      { name: 'Batch Processing', description: 'Parallel URL processing', demoContent: 'urls = ["https://site1.com", "https://site2.com"]\nresults = scraper.batch_scrape(urls, max_concurrent=5)' },
    ],
    requirements: ['Python 3.10+', 'Playwright'],
    status: 'not_downloaded',
  },
  {
    id: 'git-commit-assistant',
    name: 'Git Commit Assistant',
    description: '智能分析代码变更，自动生成符合 Conventional Commits 规范的提交信息，支持多种语言和提交风格。',
    longDescription: '# Git Commit Assistant\n\n提升团队代码提交质量的 AI 助手。\n\n## Features\n\n- **Diff 分析**: 智能解析 git diff，理解变更意图\n- **规范生成**: 遵循 Conventional Commits 标准\n- **多语言支持**: 支持 50+ 编程语言的提交信息生成\n- **风格定制**: 支持 Angular、Gitmoji 等多种风格\n- **批量处理**: 支持多个 commit 的批量重写',
    author: 'commit-master',
    version: '1.2.0',
    source: 'github',
    sourceUrl: 'https://github.com/example/git-commit-assistant',
    tags: ['Git', 'Automation', 'CLI', 'Tool', 'DevOps'],
    rating: 4.4,
    downloadCount: 18600,
    createdAt: '2023-07-10T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
    features: [
      { name: '智能 Diff 分析', description: '解析代码变更并理解修改意图', demoContent: '# 分析当前变更\ngca --analyze\n# 输出: feat(auth): 添加 JWT 令牌刷新机制' },
      { name: '批量 Commit 重写', description: '批量规范化历史提交', demoContent: 'gca --rewrite --range HEAD~5..HEAD\n# 将最近 5 个 commit 重写为规范格式' },
      { name: '多风格支持', description: 'Angular/Gitmoji/自定义风格', demoContent: 'gca --style gitmoji\n# 输出: 🎉 feat: 初始化项目结构' },
    ],
    requirements: ['Git 2.20+', 'Node.js 16+'],
    status: 'not_downloaded',
  },
  {
    id: 'code-security-scanner',
    name: 'Code Security Scanner',
    description: '全面的代码安全审计工具，检测 OWASP Top 10 漏洞、硬编码密钥、依赖风险及代码注入等安全问题。',
    longDescription: '# Code Security Scanner\n\n企业级代码安全审计工具。\n\n## Features\n\n- **漏洞扫描**: 检测 SQL 注入、XSS、CSRF 等 OWASP 漏洞\n- **密钥检测**: 扫描硬编码的 API Key、密码和 Token\n- **依赖审计**: 检查第三方依赖的已知 CVE 漏洞\n- **IaC 扫描**: 检测 Terraform/K8s 配置中的安全风险\n- **报告生成**: 生成 HTML/PDF/JSON 格式的审计报告',
    author: 'security-team',
    version: '2.3.1',
    source: 'github',
    sourceUrl: 'https://github.com/example/code-security-scanner',
    tags: ['Security', 'Audit', 'Python', 'CLI', 'DevOps'],
    rating: 4.6,
    downloadCount: 23100,
    createdAt: '2023-05-08T00:00:00Z',
    updatedAt: '2024-12-10T00:00:00Z',
    features: [
      { name: 'SAST 扫描', description: '静态代码安全分析', demoContent: 'css scan --path ./src --format json\n# 发现 3 个高危漏洞: SQL注入(1), XSS(2)' },
      { name: '密钥检测', description: '扫描硬编码敏感信息', demoContent: 'css secrets --path .\n# 发现 2 个暴露的 API Key, 1 个 AWS Secret Key' },
      { name: '依赖审计', description: '检查依赖包已知漏洞', demoContent: 'css audit --dependency-file package.json\n# 发现 5 个CVE(严重1, 高危2, 中危2)' },
    ],
    requirements: ['Python 3.9+', 'Node.js 16+'],
    status: 'not_downloaded',
  },
  {
    id: 'docker-compose-manager',
    name: 'Docker Compose Manager',
    description: '可视化管理 Docker Compose 服务，一键生成编排文件，监控容器状态，支持多环境部署配置。',
    longDescription: '# Docker Compose Manager\n\n简化 Docker Compose 管理的得力助手。\n\n## Features\n\n- **可视化编排**: 交互式生成 docker-compose.yml\n- **多环境管理**: 开发/测试/生产环境配置切换\n- **服务监控**: 实时查看容器状态和资源占用\n- **网络配置**: 自动管理容器网络和端口映射\n- **扩展模板**: 200+ 预置服务模板（Nginx、Redis、PostgreSQL 等）',
    author: 'docker-labs',
    version: '1.0.0',
    source: 'github',
    sourceUrl: 'https://github.com/example/docker-compose-manager',
    tags: ['Docker', 'DevOps', 'CLI', 'Automation', 'Web'],
    rating: 4.5,
    downloadCount: 15300,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-12-08T00:00:00Z',
    features: [
      { name: '服务编排', description: '交互式生成 Compose 文件', demoContent: 'dcm create --services "nginx,postgres,redis" --network bridge\n# 生成完整的 docker-compose.yml' },
      { name: '多环境切换', description: '开发/测试/生产配置分离', demoContent: 'dcm env switch production\n# 切换到生产环境配置，自动调整端口和资源限制' },
      { name: '状态监控', description: '实时容器资源监控', demoContent: 'dcm monitor --watch\n# ┌─────────┬──────┬────────┬────────┐\n# │ SERVICE │ CPU  │ MEM    │ DISK   │\n# ├─────────┼──────┼────────┼────────┤' },
    ],
    requirements: ['Docker 20.10+', 'Docker Compose 2.0+'],
    status: 'not_downloaded',
  },
  {
    id: 'api-testing-suite',
    name: 'API Testing Suite',
    description: '自动化 API 测试工具，支持 REST/GraphQL/gRPC 协议，自动生成测试用例，监控接口响应和性能指标。',
    longDescription: '# API Testing Suite\n\n全协议支持的 API 自动化测试平台。\n\n## Features\n\n- **多协议支持**: REST、GraphQL、gRPC、WebSocket\n- **用例生成**: 根据 OpenAPI/Swagger 自动生成测试用例\n- **断言引擎**: 支持 JSONPath、XPath、正则表达式验证\n- **性能测试**: 内置压测工具，监控响应时间与吞吐量\n- **Mock 服务**: 根据 API 定义自动启动 Mock Server',
    author: 'api-labs',
    version: '2.0.0',
    source: 'github',
    sourceUrl: 'https://github.com/example/api-testing-suite',
    tags: ['API', 'Testing', 'Automation', 'Web', 'CLI', 'Python'],
    rating: 4.3,
    downloadCount: 19700,
    createdAt: '2023-10-22T00:00:00Z',
    updatedAt: '2024-12-05T00:00:00Z',
    features: [
      { name: '自动用例生成', description: '从 Swagger/OpenAPI 生成测试', demoContent: 'ats generate --spec ./openapi.yaml\n# 自动生成 42 个测试用例覆盖所有端点' },
      { name: '多协议支持', description: 'REST/GraphQL/gRPC 一站式测试', demoContent: 'ats test --endpoint https://api.example.com/graphql \\\n  --query "query { users { id name } }"' },
      { name: '性能压测', description: '接口压力测试与性能分析', demoContent: 'ats bench --endpoint /api/orders --concurrency 50 --duration 30s\n# 平均响应: 125ms | P99: 340ms | QPS: 420' },
    ],
    requirements: ['Node.js 18+', 'OpenAPI 3.0+'],
    status: 'not_downloaded',
  },
];
